### ISSUE TITLE
not able to compile with GNURadio 3.7

### ISSUE THREAD

**Issue by patel999jay** [michelbarbeau/gr-uwspr#1]
Hi,

I am trying to build gr-uwspr module with GNURadio 3.7 on Ubuntu 16, but could not be able to build it. Here is Error Snippet.

```bash
jay@jay-Inspiron-5459:~/gr-uwspr/build$ sudo make
[sudo] password for jay: 
Scanning dependencies of target gnuradio-uwspr
[  3%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/helpers.cc.o
[  6%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/c2file_source_impl.cc.o
[ 10%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/Fano.cc.o
[ 13%] Building C object lib/CMakeFiles/gnuradio-uwspr.dir/tab.c.o
[ 17%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/WSPR_unpacker_impl.cc.o
[ 20%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/sync_and_demodulate_impl.cc.o
[ 24%] Building CXX object lib/CMakeFiles/gnuradio-uwspr.dir/slm.cc.o
/home/jay/gr-uwspr/lib/slm.cc: In member function ‘float gr::uwspr::SLM::slmFrequencyDrift(gr::uwspr::mode_nonlinear, float, float)’:
/home/jay/gr-uwspr/lib/slm.cc:60:10: error: ‘abs’ was not declared in this scope
          );
          ^
lib/CMakeFiles/-uwspr.dir/build.make:206: recipe for target 'lib/CMakeFiles/gnuradio-uwspr.dir/slm.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-uwspr.dir/slm.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-uwspr.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-uwspr.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Can you please point me in the right direction ?

Thanks.

**Comment by patel999jay** [comment]
#2 Updated Dependencies
